;; -*- mode: eask; lexical-binding: t -*-

(package "gt-cli"
         "1.0.0"
         "A command-line interface for gt")

(website-url "https://github.com/emacs-eine/gt-cli")
(keywords "convenience")

(package-file "gt-cli.el")
(files "bin")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source 'gnu)
(source 'melpa)
(source 'jcs-elpa)

(depends-on "emacs" "28.1")
(depends-on "gt")
(depends-on "commander")
(depends-on "msgu")
